// Curated table of famous named motorcycle rides near the trip.
// Each ride is OSRM-routed endpointA -> via... -> endpointB at build time to get
// real road geometry. Endpoint coords only need to be close enough to snap to the
// correct road; lengthMi/curves/blurb/status are metadata shown in the app.
//
// Sourced from a multi-agent research + adversarial-verification pass (web-checked
// for current 2026 status, incl. Hurricane Helene closures) and refined against the
// map. Add/adjust freely, then: node scripts/build-data.mjs --step rides
//
// currentlyRideable=false greys the line/card and shows a warning (road not a clean
// through-ride right now); the status text always carries the detail.

export const RIDES = [
  {
    id: 'tail-of-the-dragon',
    name: 'Tail of the Dragon',
    road: 'US-129',
    region: 'NC/TN border — Deals Gap',
    difficulty: 'expert',
    curves: 318,
    lengthMi: 11,
    nearDealsGapMi: 0,
    currentlyRideable: true,
    blurb: 'The most famous motorcycle road in America: 318 curves in 11 miles with no intersections, driveways or scenery to distract you. A relentless, blind, decreasing-radius ballet — the literal front door of your base camp.',
    status: 'Open as of June 2026. The Dragon stayed open through Hurricane Helene (it’s the through-route between Deals Gap and Chilhowee Lake). 30 mph limit, heavily enforced — tickets for touching the double-yellow; watch for gravel, cyclists, and heavy LEO/photographer presence. Deals Gap Motorcycle Resort reopened Feb 27, 2026. Ride early to beat traffic.',
    endpointA: { name: 'Deals Gap (NC/TN state line, US-129)', lat: 35.4664, lon: -83.9215 },
    endpointB: { name: 'Tabcat Creek Bridge, TN', lat: 35.5156, lon: -83.9899 },
  },
  {
    id: 'moonshiner-28',
    name: 'Moonshiner 28 (Hellbender)',
    road: 'NC-28',
    region: 'Deals Gap ↔ Stecoah / Fontana, NC',
    difficulty: 'moderate',
    curves: null,
    lengthMi: 38,
    nearDealsGapMi: 2,
    currentlyRideable: true,
    blurb: 'Where the Dragon ends, the Moonshiner begins: sweeping curves and big elevation changes past Cheoah Lake and Fontana Dam with prohibition-era smuggling lore and a fraction of US-129’s crowds. The first miles out of the Gap are nicknamed "Hellbender 28."',
    status: 'Open and rideable as of 2026. Graham County reports all roads in/out open with no advisories; the Fontana–Stecoah corridor was largely spared by Helene. A few Nantahala-area forest spur roads may still have lingering closures — confirm spurs locally.',
    endpointA: { name: 'Deals Gap (US-129 / NC-28 junction), NC', lat: 35.4677, lon: -83.9192 },
    endpointB: { name: 'NC-28 / NC-143 near Stecoah Gap, NC', lat: 35.3389, lon: -83.6486 },
    via: [{ name: 'Fontana Dam Road area, NC-28', lat: 35.4259, lon: -83.7905 }],
  },
  {
    id: 'cherohala-skyway',
    name: 'Cherohala Skyway',
    road: 'NC-143 / TN-165',
    region: 'Robbinsville NC ↔ Tellico Plains TN',
    difficulty: 'moderate',
    curves: null,
    lengthMi: 43,
    nearDealsGapMi: 7,
    currentlyRideable: true,
    blurb: 'A 43-mile high-elevation masterpiece cresting over 5,000 ft, with sweeping engineered curves, mile-high overlooks and almost no traffic. The fast, flowing antidote to the Dragon’s intensity.',
    status: 'Open (2026). Sits on high ridgelines, largely spared by Helene. Caveats: history of short rain-driven washouts; high and exposed with fog/cold even in summer; and genuinely NO FUEL for the full ~43 mi, so top off first. Check TDOT SmartWay before riding.',
    endpointA: { name: 'Robbinsville, NC (NC-143)', lat: 35.3232, lon: -83.8071 },
    endpointB: { name: 'Tellico Plains, TN (TN-165 west end)', lat: 35.3636, lon: -84.2972 },
    via: [{ name: 'Santeetlah / Stratton Gap (crest)', lat: 35.3318, lon: -84.0125 }],
  },
  {
    id: 'wayah-road',
    name: 'Wayah Road',
    road: 'NC-1310',
    region: 'Nantahala Gorge ↔ Franklin, NC',
    difficulty: 'challenging',
    curves: null,
    lengthMi: 28,
    nearDealsGapMi: 22,
    currentlyRideable: true,
    blurb: 'A locals’ hidden gem climbing from the Nantahala Gorge along the river to alpine Nantahala Lake, over Wayah Gap, then plunging east through tight switchbacks to Franklin. Remote, tree-tunneled and technical.',
    status: 'Open for the 2026 season; no active full closure on USFS/NCDOT/DriveNC. Genuinely landslide-prone — narrow with loose gravel after rain and no services mid-route. Verify same-day on DriveNC.gov and with the Nantahala Ranger District.',
    endpointA: { name: 'Nantahala / Beechertown, NC (US-19/74)', lat: 35.3320, lon: -83.6480 },
    endpointB: { name: 'Franklin, NC (US-64 junction)', lat: 35.1808, lon: -83.4546 },
    via: [{ name: 'Nantahala Lake, NC', lat: 35.2249, lon: -83.6385 }],
  },
  {
    id: 'foothills-parkway-west',
    name: 'Foothills Parkway West',
    road: 'Foothills Pkwy',
    region: 'Walland ↔ Wears Valley, TN',
    difficulty: 'easy',
    curves: null,
    lengthMi: 16,
    nearDealsGapMi: 25,
    currentlyRideable: true,
    blurb: 'A flowing, immaculately paved NPS ridge-top parkway with viaducts soaring across the valleys (the 2018 "Missing Link") and unobstructed views of the Smokies’ crest. A relaxed warm-down or sunset cruise after the Dragon.',
    status: 'Open (verified June 2026). This is Foothills Parkway WEST, on the TN side, outside Helene’s damage zone. 45 mph, no commercial traffic. Only routine winter ice and short maintenance closures occur; confirm day-of on nps.gov/grsm.',
    endpointA: { name: 'Walland, TN (US-321 west entrance)', lat: 35.6911, lon: -83.8156 },
    endpointB: { name: 'Wears Valley, TN (east terminus)', lat: 35.6957, lon: -83.6447 },
  },
  {
    id: 'newfound-gap-road',
    name: 'Newfound Gap Road',
    road: 'US-441',
    region: 'Great Smoky Mountains NP (Cherokee ↔ Gatlinburg)',
    difficulty: 'moderate',
    curves: null,
    lengthMi: 31,
    nearDealsGapMi: 30,
    currentlyRideable: true,
    blurb: 'The only road over the crest of the Smokies: long, scenic, well-graded sweepers climbing to the 5,046-ft Newfound Gap with sweeping Appalachian panoramas. A grand-touring classic through the most-visited national park in the US.',
    status: 'Open 24/7 as of 2026. Reopened Sept 12, 2025 after repair of an Aug 2025 TN-side washout (a local rain event, not Helene). Expect occasional single-lane construction; heavy tourist traffic, bears/elk, and weather can cause temporary closures.',
    endpointA: { name: 'Oconaluftee / Cherokee, NC entrance', lat: 35.5145, lon: -83.3070 },
    endpointB: { name: 'Sugarlands / Gatlinburg, TN entrance', lat: 35.6870, lon: -83.5370 },
    via: [{ name: 'Newfound Gap (NC/TN crest)', lat: 35.6110, lon: -83.4250 }],
  },
  {
    id: 'the-rattler-nc-209',
    name: 'The Rattler (NC-209)',
    road: 'NC-209',
    region: 'Lake Junaluska ↔ Hot Springs, NC',
    difficulty: 'challenging',
    curves: 234,
    lengthMi: 36.6,
    nearDealsGapMi: 60,
    currentlyRideable: true,
    blurb: 'Thirty-six miles of relentless sweepers, tight off-camber switchbacks and elevation change from Lake Junaluska up through Trust and Luck to the French Broad at Hot Springs — Dragon-grade twisties with a fraction of the crowds.',
    status: 'Open (2026). NC-209 mainline reopened after Helene; residual truck/weight limits don’t affect bikes. One weekday-only one-lane signal at the Hot Springs end (new French Broad bridge) — both lanes flow on weekends.',
    endpointA: { name: 'Lake Junaluska, NC (US-23/74)', lat: 35.5269, lon: -82.9610 },
    endpointB: { name: 'Hot Springs, NC (US-25/70)', lat: 35.8929, lon: -82.8290 },
    via: [{ name: 'Trust, NC', lat: 35.7480, lon: -82.8850 }],
  },
  {
    id: 'six-gap-north-georgia',
    name: 'Six Gap North Georgia',
    road: 'GA-60 / GA-180 / US-19-129 / GA-348',
    region: 'North Georgia (Suches loop)',
    difficulty: 'expert',
    curves: null,
    lengthMi: 77,
    nearDealsGapMi: 50,
    currentlyRideable: true,
    blurb: 'The legendary figure-eight linking six mountain gaps — Woody, Neels, Jacks, Unicoi, Hogpen and Wolfpen — around Blood Mountain. ~77 miles of near-continuous curves anchored at the TWO Wheels of Suches resort.',
    status: 'Open for June 2026. All component roads are clear; North Georgia largely escaped lasting Helene damage and TWO Wheels of Suches is operating. GA-348 over Hogpen Gap closes periodically in winter for ice — not a June concern.',
    endpointA: { name: 'Suches, GA (TWO Wheels of Suches)', lat: 34.7174, lon: -84.0381 },
    endpointB: { name: 'Suches, GA (TWO Wheels of Suches)', lat: 34.7174, lon: -84.0381 },
    via: [
      { name: 'Woody Gap (GA-60)', lat: 34.6786, lon: -84.0017 },
      { name: 'Neels Gap / Walasi-Yi (US-19/129)', lat: 34.7400, lon: -83.9189 },
      { name: 'Hogpen Gap (GA-348)', lat: 34.7556, lon: -83.8447 },
      { name: 'Wolf Pen Gap (GA-180)', lat: 34.7556, lon: -83.9786 },
    ],
  },
  {
    id: 'richard-russell-scenic-hwy-ga-348',
    name: 'Richard B. Russell Scenic Hwy',
    road: 'GA-348',
    region: 'North Georgia (Helen ↔ Choestoe)',
    difficulty: 'challenging',
    curves: null,
    lengthMi: 22,
    nearDealsGapMi: 60,
    currentlyRideable: true,
    blurb: 'A federally designated scenic byway threading over Hogpen Gap with sweeping high-speed bends, 7% sustained grades and panoramic Blue Ridge overlooks. Remote, smooth and lightly trafficked.',
    status: 'Open for June 2026. Periodic winter closures for snow/ice (closed Feb 2025) but clear in summer. Watch for gravel, fallen leaves and cyclists on the Hogpen Gap climb.',
    endpointA: { name: 'GA-75A near Helen, GA', lat: 34.7361, lon: -83.7589 },
    endpointB: { name: 'GA-180 near Choestoe / Vogel, GA', lat: 34.7846, lon: -83.9203 },
    via: [{ name: 'Hogpen Gap overlook', lat: 34.7556, lon: -83.8447 }],
  },
  {
    id: 'brasstown-bald-summit-road',
    name: 'Brasstown Bald Summit Road',
    road: 'GA-180 Spur',
    region: 'North Georgia (Towns Co.)',
    difficulty: 'moderate',
    curves: null,
    lengthMi: 2.5,
    nearDealsGapMi: 58,
    currentlyRideable: true,
    blurb: 'The short, steep, hairpin-laced spur to the parking lot below Georgia’s 4,784-ft high point — the highest paved road in the state. A bucket-list dead-end with 360° summit views; ride it for the destination, not pace.',
    status: 'Open seasonally for 2026 (roughly May–Oct; closed in winter). Paid gate: ~$10/person. Narrow, steep, low limits and a 0.6-mi hike or shuttle from the upper lot to the tower. Not affected by Helene.',
    endpointA: { name: 'Jacks Gap (GA-180 junction), GA', lat: 34.8567, lon: -83.8089 },
    endpointB: { name: 'Brasstown Bald summit parking, GA', lat: 34.8742, lon: -83.8108 },
  },
  {
    id: 'devils-triangle-116',
    name: 'Devil’s Triangle (TN-116)',
    road: 'TN-116',
    region: 'East Tennessee (Cumberland Plateau, near Wartburg)',
    difficulty: 'expert',
    curves: null,
    lengthMi: 44,
    nearDealsGapMi: 70,
    currentlyRideable: true,
    blurb: 'The brutal heart of the 44-mile Devil’s Triangle loop, climbing Fork Mountain through the tight, guardrail-free "Devil’s Stairway" switchbacks at Armes Gap. Gravel patches, blind drop-offs and the odd coal truck make it more punishing than the Dragon.',
    status: 'Open in 2026. On the Cumberland Plateau, well west of Helene’s zone. It’s a rough rural mountain road, not a maintained scenic route — expect gravel/debris, potholes, ATVs and occasional coal/log trucks; avoid in winter or heavy rain.',
    endpointA: { name: 'TN-62 / TN-116 near Petros, TN', lat: 36.0820, lon: -84.4320 },
    endpointB: { name: 'Caryville, TN (TN-116 at I-75)', lat: 36.2970, lon: -84.2190 },
    via: [{ name: 'Armes Gap / "Devil’s Stairway"', lat: 36.1430, lon: -84.3140 }],
  },
  {
    id: 'diamondback-226a',
    name: 'The Diamondback (NC-226A)',
    road: 'NC-226A',
    region: 'Marion ↔ Little Switzerland, NC',
    difficulty: 'challenging',
    curves: 190,
    lengthMi: 12,
    nearDealsGapMi: 95,
    currentlyRideable: true,
    blurb: 'Roughly 190 curves in a dozen miles as NC-226A corkscrews up the escarpment to Little Switzerland in a relentless cascade of switchbacks, dropping ~2,000 ft. A compact, intense climb beloved by sportbike riders.',
    status: 'The 226A climb itself is open and fully rideable in 2026. BUT the adjacent Blue Ridge Parkway (Mt. Mitchell MP ~355 north through Little Switzerland MP ~334) remains CLOSED from Helene (reopen expected late 2026), so the classic ~38-mi Diamondback loop is broken — reroute on local roads (NC-226, US-221, NC-80).',
    endpointA: { name: 'US-221 / NC-226 near Woodlawn (Marion), NC', lat: 35.7900, lon: -82.0030 },
    endpointB: { name: 'Gillespie Gap / BRP MP 331, Little Switzerland', lat: 35.8380, lon: -82.0780 },
  },
  {
    id: 'copperhead-loop',
    name: 'The Copperhead Loop',
    road: 'US-276 / NC-215 / US-64',
    region: 'Brevard / Pisgah Forest, NC',
    difficulty: 'challenging',
    curves: null,
    lengthMi: 81,
    nearDealsGapMi: 95,
    currentlyRideable: true,
    blurb: 'An 80-mile loop stitching US-276, the Blue Ridge Parkway and NC-215 through Pisgah’s waterfall country with eight named falls and endless forest curves. A full-day named route combining two of WNC’s best technical roads.',
    status: 'Open as of June 2026. The loop’s BRP link (US-276 MP ~412 to NC-215 MP 423) reopened after Helene; NC-215 through Lake Logan reopened Feb 2025. Remaining BRP Helene closures are far north and don’t affect this loop. Re-check NPS BRP status before riding.',
    endpointA: { name: 'US-276 / US-64, Pisgah Forest, NC', lat: 35.2640, lon: -82.7140 },
    endpointB: { name: 'US-64 / NC-215 near Rosman, NC', lat: 35.1450, lon: -82.8420 },
    via: [
      { name: 'Pisgah Inn (BRP, US-276 top)', lat: 35.4030, lon: -82.7560 },
      { name: 'NC-215 / BRP at Beech Gap', lat: 35.3220, lon: -82.9180 },
    ],
  },
  {
    id: 'nc-215-pisgah',
    name: 'NC-215 (Pisgah / Balsam Grove)',
    road: 'NC-215',
    region: 'Rosman ↔ Lake Logan, NC (Pisgah)',
    difficulty: 'challenging',
    curves: null,
    lengthMi: 17,
    nearDealsGapMi: 90,
    currentlyRideable: true,
    blurb: 'A tight, technical ribbon up the West Fork of the Pigeon River through the Pisgah high country, climbing to the Blue Ridge Parkway at Beech Gap. Endless well-canted hairpins and waterfalls, lightly trafficked — a connoisseur’s road.',
    status: 'Open in 2026 (a state highway, not the Parkway). The Beech Gap junction with the BRP (MP 423) is reachable — the MP 422 Devil’s Courthouse slide repair completed Aug 2025; Lake Logan section reopened Feb 2025. Verify the Lake Logan half on DriveNC.gov.',
    endpointA: { name: 'US-64 near Rosman, NC', lat: 35.1450, lon: -82.8420 },
    endpointB: { name: 'Blue Ridge Pkwy at Beech Gap, NC', lat: 35.3220, lon: -82.9180 },
    via: [{ name: 'Balsam Grove, NC', lat: 35.2470, lon: -82.8870 }],
  },
  {
    id: 'the-snake-421',
    name: 'The Snake (US-421)',
    road: 'US-421',
    region: 'NE Tennessee (Mountain City ↔ Bristol)',
    difficulty: 'challenging',
    curves: 489,
    lengthMi: 33,
    nearDealsGapMi: 105,
    currentlyRideable: true,
    blurb: '489 curves over three mountains and the postcard bowl of Shady Valley, with the namesake country store as rider HQ. A relentless, technical northeast-Tennessee classic.',
    status: 'Open in 2026. The road came through Helene and was cleared quickly. Backbone Rock day-use (TN-133 side trip) reopened Mar 2026 and its campground Apr 2026. Minor side-road recovery work possible but the US-421 mainline is clear.',
    endpointA: { name: 'Mountain City, TN (US-421/TN-67)', lat: 36.4050, lon: -81.8030 },
    endpointB: { name: 'South Holston Lake / Bristol, TN', lat: 36.5260, lon: -82.0080 },
    via: [{ name: 'Shady Valley Country Store', lat: 36.5630, lon: -81.8810 }],
  },
  {
    id: 'roan-mountain-143',
    name: 'Roan Mountain (TN-143)',
    road: 'TN-143',
    region: 'NE Tennessee ↔ Carvers Gap (TN/NC line)',
    difficulty: 'challenging',
    curves: null,
    lengthMi: 12.5,
    nearDealsGapMi: 120,
    currentlyRideable: true,
    blurb: 'A steady climb of tight switchbacks through Cherokee National Forest to 5,500-ft Carvers Gap, gateway to the open grassy balds of the Roan Highlands. The payoff views and cool mountain air are unmatched in the region.',
    status: 'Open (2026). TN-143 up to Carvers Gap is not on TDOT’s remaining Helene closure list. Caveats are park-internal: Roan Mountain SP upper campground loops remain closed for a rebuild; day-use reopening ~late May 2026. Expect work zones; verify on TDOT SmartWay.',
    endpointA: { name: 'Roan Mountain, TN (US-19E)', lat: 36.1980, lon: -82.0750 },
    endpointB: { name: 'Carvers Gap, TN/NC line', lat: 36.1060, lon: -82.1100 },
  },
  {
    id: 'back-of-the-dragon',
    name: 'Back of the Dragon',
    road: 'VA-16',
    region: 'Tazewell ↔ Marion, VA',
    difficulty: 'challenging',
    curves: 438,
    lengthMi: 32,
    nearDealsGapMi: 130,
    currentlyRideable: true,
    blurb: 'Virginia’s signature sport road: 32 miles climbing over three mountain ranges with 3,500 ft of elevation change and named curves like Zero Gravity and Cliff Hanger. A genuine rival to its Tennessee namesake.',
    status: 'Open as of June 2026. VDOT lists Route 16 pavement work complete with no active closures. A Tazewell County bridge replacement is planned but not until ~2028. Not in the Helene corridor; the RT16 Rally is scheduled for June 2026.',
    endpointA: { name: 'Marion, VA', lat: 36.8346, lon: -81.5147 },
    endpointB: { name: 'Tazewell, VA', lat: 37.1240, lon: -81.5190 },
    via: [{ name: 'VA-16 crest near Hungry Mother', lat: 36.9500, lon: -81.5230 }],
  },
  {
    id: 'blue-ridge-parkway-virginia',
    name: 'Blue Ridge Parkway (VA Highlands)',
    road: 'Blue Ridge Pkwy (VA)',
    region: 'Waynesboro ↔ Roanoke, VA',
    difficulty: 'easy',
    curves: null,
    lengthMi: 120,
    nearDealsGapMi: 230,
    currentlyRideable: false,
    blurb: 'The Virginia run of America’s most beloved scenic road: endless gentle sweepers along the ridgeline past the Peaks of Otter, no commercial traffic, a 45 mph rhythm built for savoring. The signature spine of the trip’s northern approach.',
    status: 'PARTIALLY CLOSED June 2026 — not a clean through-ride. A multi-year project has MP 105.8–112.4 (US-460 area, just south of Peaks of Otter) closed to vehicles (reopen targeted Fall 2026); James River bridge MP 63.5–63.9 and the Roanoke Mountain Loop are also closed. North of Peaks of Otter is rideable; the southern leg needs an off-Parkway detour. (The main trip route already handles this.)',
    endpointA: { name: 'Rockfish Gap / Waynesboro, VA', lat: 37.9120, lon: -78.8990 },
    endpointB: { name: 'Roanoke, VA (US-220)', lat: 37.3380, lon: -79.8770 },
    via: [{ name: 'Peaks of Otter', lat: 37.4450, lon: -79.6060 }],
  },
  {
    id: 'skyline-drive',
    name: 'Skyline Drive',
    road: 'Skyline Drive',
    region: 'Shenandoah National Park, VA',
    difficulty: 'easy',
    curves: null,
    lengthMi: 105,
    nearDealsGapMi: 270,
    currentlyRideable: true,
    blurb: '105 miles of ridge-top cruising through Shenandoah National Park, with 75 overlooks and frequent black-bear and deer sightings. A meditative, low-speed scenic icon that connects to the Blue Ridge Parkway at its south end.',
    status: 'Open end to end (NPS Skyline Drive status). 35 mph strictly enforced; per-vehicle entrance fee. No park-wide timed entry (reservations apply only to Old Rag hikers). Far north of Helene damage. Seasonal weather/ice/wildlife closures possible.',
    endpointA: { name: 'Front Royal Entrance, VA', lat: 38.8650, lon: -78.1980 },
    endpointB: { name: 'Rockfish Gap, VA', lat: 37.9120, lon: -78.8990 },
    via: [{ name: 'Skyland / Thorofare Mtn', lat: 38.5950, lon: -78.3760 }],
  },
  {
    id: 'reddish-knob-us33',
    name: 'Reddish Knob / US-33 West',
    road: 'US-33',
    region: 'Harrisonburg, VA ↔ WV line',
    difficulty: 'challenging',
    curves: null,
    lengthMi: 21,
    nearDealsGapMi: 300,
    currentlyRideable: true,
    blurb: 'A tight, technical climb of hairpins and 9% grades up Shenandoah Mountain that locals swear rivals the Dragon, capped by an optional spur to the 4,397-ft summit of Reddish Knob. A hidden gem west of Harrisonburg.',
    status: 'Open in 2026. US-33 over Shenandoah Mountain (GW National Forest) is well north of Helene and unaffected; a safety-widening finished summer 2025. Standard forest cautions: gravel/limbs after storms; the paved Reddish Knob summit spur is gated in winter.',
    endpointA: { name: 'Rawley Springs, VA', lat: 38.5050, lon: -79.0560 },
    endpointB: { name: 'WV State Line (Shenandoah Mtn)', lat: 38.4640, lon: -79.2280 },
  },
];
